#!/bin/bash
# selenium-node - this script starts and stops the selenium node
#
# chkconfig:   - 2345 85 15
# description: Selenium Node is a process that connects to Selenium Grid
# processname: selenium_node
# pidfile:     /var/run/selenium/selenium_node.pid

# Source function library.
. /etc/rc.d/init.d/functions
. ./seleniumops.conf

ERROR_LOG=$LOG_DIR/selenium_node_error.log
STD_LOG=$LOG_DIR/selenium_node_std.log
PIDFILE=/var/run/selenium/selenium_node.pid
JAVA=`which java`
HOST=`hostname`
DISPLAY=$STARTING_DISPLAY
SELENIUM_PORT=$SELENIUM_START_PORT

start() {
    if test -f $PIDFILE
    then
        PID=`cat $PIDFILE`
        if  ps --pid $PID >/dev/null;
            then
                echo "Selenium node is already running: $PID"
                exit 0
            else
                echo "Removing stale pid file: $PIDFILE"
        fi
      fi

    echo -n "Starting Selenium node..."
    daemon --user "$USER" "DISPLAY=:$DISPLAY $JAVA -jar $SELENIUM -role node -hub $SELENIUM_HUB"/grid/register" -port $SELENIUM_PORT -host $HOST -nodeConfig $NODE_CFG >$STD_LOG 2>$ERROR_LOG &"
    echo
    ps -u $USER -o pid,user,command | grep -i 'role[[:space:]]node' | awk {'print $1 '} > $PIDFILE
}

stop() {
    if test -f $PIDFILE
    then
        echo -n "Stopping Selenium node..."
        PID=`cat $PIDFILE`
        su $user -c "kill -3 $PID"
        if kill -9 $PID ;
                then
                        sleep 2
                        test -f $PIDFILE && rm -f $PIDFILE
                        success
                else
                        echo -n "Selenium node could not be stopped..."
                        failure
                fi
    else
            echo "Selenium node is not running."
            failure
    fi
    echo
}

status() {
    if test -f $PIDFILE
    then
        PID=`cat $PIDFILE`
        if  ps --pid $PID >/dev/null ;
        then
            echo "Selenium node is running...$PID"
        else
            echo "Selenium node isn't running..."
        fi
    else
            echo "Selenium node isn't running..."
    fi
}

case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        stop
        start
        ;;
    status)
        $1
        ;;
    *)
        echo "Usage: $SELF start|stop|restart|status"
        exit 1
    ;;
esac
